name: dictionary_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-166.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  http: ^0.13.6
  audioplayers: ^4.1.0
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/inconsolata/Inconsolata-VariableFont_wdth,wght.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/lora/Lora-VariableFont_wght.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-VariableFont_slnt,wght.ttf
        
